
Vagrant.configure("2") do |config|

  config.vm.define "ts.elastomic", primary: true do |cfg|
    cfg.vm.box = "elastomic-box-vmware"
    # below version points to latest dev-testboxes commit hash
    #cfg.vm.box_version = "0.9.9520c3b"
    cfg.vm.hostname = "elastomic"
    cfg.disksize.size = "256GB"
    cfg.vm.synced_folder '.', '/vagrant', disabled: true
    cfg.vm.network "private_network", ip: "192.168.33.10"
    cfg.vm.network "forwarded_port", guest: 5601, host: 5601
    cfg.vm.network "forwarded_port", guest: 9200, host: 9200
    cfg.vm.network "forwarded_port", guest: 8487, host: 8487
    cfg.vm.network "forwarded_port", guest: 8888, host: 8888
    cfg.vm.provider :vmware_desktop do |vmw|
      vmw.vmx["displayname"] = "ts.elastomic"
      vmw.vmx["ethernet0.pcislotnumber"] = "32"
      vmw.vmx["ethernet1.pcislotnumber"] = "33"
      # Enable this setting because of a possible bug in Workstation that doesn't forward the port properly.
      #vmw.ssh_info_public = true
      vmw.memory = 5000
      vmw.cpus = 2
      #vmw.customize ["modifyvm", :id, "--cableconnected1", "on"]
    end

    cfg.vm.provision "shell" do |s2|
    s2.path = "./scripts/install-fleet-server.sh"
    s2.env = {
        "ELASTIC_STACK_VERSION" => "7.14.0",
        "KIBANA_URL" => "http://192.168.33.10:5601",
        "KIBANA_AUTH" => "vagrant:vagrant",
        "ELASTICSEARCH_URL" => "http://192.168.33.10:9200"
    }
    end


    # Setup the Elastic Stack
    cfg.vm.provision "shell" do |s|
      s.path = "./scripts/setup-elastic.sh"
      s.env = {
        "ELASTIC_STACK_VERSION" => "7.14.0",
        "KIBANA_URL" => "http://192.168.33.10:5601",
        "KIBANA_AUTH" => "vagrant:vagrant",
        "ELASTICSEARCH_URL" => "http://192.168.33.10:9200",
        "FLEET_SERVER_URL" => "https://192.168.33.10:8220"
      }
    end
  end

  config.vm.define "ts.windows10" do |cfg|
    cfg.vm.box = "windows-box-vmware"
    # below version points to latest dev-testboxes commit hash
    # cfg.vm.box_version = "0.9.1608145966"
    cfg.vm.hostname = "windows10"
    cfg.vbguest.auto_update = true
    cfg.vm.network "private_network", ip: "192.168.33.11", auto_config: true

    config.vm.network "forwarded_port", guest: 3389, host: 33389, auto_correct: true
    cfg.vm.guest = "windows"
    cfg.vm.communicator = "winrm"
    
    cfg.vm.provider :vmware_desktop do |vmw, override|
      vmw.vmx["displayname"] = "ts.windows10"
      vmw.memory = 2048
      vmw.cpus = 2
    end

    cfg.vm.provision "exprfix", type: "shell", path: "./scripts/fix-windows-expiration.ps1"
    cfg.vm.provision "shutup10", type: "shell", path: "./scripts/install-shutup10config.ps1"
    cfg.vm.provision "installea", type: "shell", path: "./scripts/install-ea.ps1"
  end

  config.vm.define "ts.centos7" do |cfg|
    cfg.vm.box = "centos-box-vmware"
    # below version points to latest dev-testboxes commit hash
    # cfg.vm.box_version = "0.9.9520c3b"
    cfg.vm.hostname = "centos7"
    cfg.vbguest.auto_update = true
    cfg.vm.synced_folder '.', '/vagrant', disabled: true
    cfg.vm.network "private_network", ip: "192.168.33.12", auto_config: true
    cfg.vm.network "forwarded_port", guest: 80, host: 8080
    cfg.vm.network "forwarded_port", guest: 9090, host: 9090
    cfg.vm.provider :vmware_desktop do |vmw, override|
      vmw.vmx["displayname"] = "ts.centos7"
      vmw.ssh_info_public = true
      vmw.vmx["ethernet0.pcislotnumber"] = "32"
      vmw.memory = 1024
      vmw.cpus = 1
      #vmw.customize ["modifyvm", :id, "--cableconnected1", "on"]
    end

    # Setup Auditbeat
    cfg.vm.provision "auditbeatsetup", type: "shell", path: "./scripts/setup-linux-beats.sh"

    # Install and Enroll Elastic Agent
    cfg.vm.provision "shell" do |s|
      s.path = "./scripts/install-ea-linux.sh"
      s.env = {
        "ELASTIC_STACK_VERSION" => "7.14.0",
        "KIBANA_URL" => "http://192.168.33.10:5601",
        "KIBANA_AUTH" => "vagrant:vagrant",
        "FLEET_SERVER_URL" => "https://192.168.33.10:8220"
      }
    end
  end
end
